### ISSUE TITLE
Distinguish between e2e and ATSSS?

### ISSUE THREAD

**Issue by markusa** [SpencerDawkins/draft-dawkins-quic-what-to-do-with-multipath#8]
@SpencerDawkins 

My feeling is, that the document is too much 3GPP ATSSS related.

With #7 I started to highlight that different use case were seen from people at the interim which are not necessarely seen as part of the ATSSS. I see for example the strong Alibaba presentation and MP draft is e2e related.

**Comment by SpencerDawkins** [comment]
I have concerns about that as well, and your point is well taken. I have suggested new text on #7 - please let me know what you think. 

I am likely to ignore the distinction in this document (either someone speaking QUIC is going to do multipath to another endpoint speaking QUIC, or they aren't going to do multipath, and what happens on the other side of the multipath end-point shouldn't be relevant to the discussion of strategies in this document). But I need to say whether it matters or not in the document, rather than just act like no one noticed ... 

Does that make sense to @markusa ?

**Comment by markusa** [comment]
Hi @SpencerDawkins,

I likely have to disagree. QUIC Multipath for ATSSS has special demand on DATAGRAM and probably MASQUE, whereas e2e has this not or only limited.

Just my two cents here, if I not misunderstood the aim of the document...

**Comment by SpencerDawkins** [comment]
Hi, @markusa - I agree with what you're saying. I think we definitely need to drill down one more level (at least). 

One of the thing that the MASQUE people keep saying (not without argument) is that MASQUE proxies don't need to be aware of multipath - the idea is that you and the actual end-to-end other end are using multiple paths, but each proxy just sees part of the the connection. 

But I still need to think about this, and leaving the issue open so I don't forget is a great plan ...

**Comment by markusa** [comment]
Hi @SpencerDawkins ,

I opened another PR #10 to sharpen the difference between e2e/ATSSS in repect to sending strategies. I'm fine to keep the scope as it is on sending, however it should be mentioned that there might be other constraints (re-ordering or path/stream scheduling), not in scope of this document.

**Comment by SpencerDawkins** [comment]
Thanks for #10. I merged it (I cleaned up some missing colons on references, etc). 

I'm planning to wait a few days before submitting -02, to see where I end up.

**Comment by SpencerDawkins** [comment]
Actually, I submitted -02, because I missed a "multicast" in -01. Now, the draft in the datatracker should be sane ...
